sudo: required
services:
  - docker

before_install:
  - docker build -t anshulk09/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anshulk09/react-test npm run test

after_success:
  - docker build -t anshulk09/multi-client ./client
  - docker build -t anshulk09/multi-nginx ./nginx
  - docker build -t anshulk09/multi-server ./server
  - docker build -t anshulk09/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anshulk09/multi-client
  - docker push anshulk09/multi-nginx
  - docker push anshulk09/multi-server
  - docker push anshulk09/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-328592414232
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
